### PR TITLE
Remove ::Function from dispatch

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
`Function` in Julia is an abstract type that not all functions actually subtype. Thus there are many functions in Julia, like callable types, which are restricted from using these ODE solvers because they don't `<:Function`. However, these work perfectly fine if the requirement for `::Function` is removed, meaning that it was unncessary. Since there's no performance difference when removing them, this makes the functions work on all Julia functions without hurting the performance.

### CODE REVIEW

**Comment by luchr** [comment]
Then I have to change a litte bit more, e.g. here
```julia
type BvpsolInternalCallInfos{FInt<:FortranInt, RHS_F<:Function, 
        BC_F<:Function, ODESOL_F<:Function} <: ODEinternalCallInfos
```
removing the `Function`, too, because the `rhs` is saved there.

Do you have a simple example for such an callable type, so that I can test this?

**Comment by ChrisRackauckas** [comment]
```julia
struct Lorenz
  a::Float64
  b::Float64
  c::Float64
end
function (p::Lorenz)(t,u,du)
   du[1] = p.a*(u[2]-u[1])
   du[2] = u[1]*(p.b-u[3]) - u[2]
   du[3] = u[1]*u[2] - p.c*u[3]
end
f = Lorenz(10.0,28.0,8/3)
# Now f(t,u,du) is a function which doesn't `<:Function`
```

**Comment by luchr** [comment]
I'm in the middle of finalizing a new `ODEInterface` version in order to include an interface to the Fortran 2003 [BVP_M-2 boundary solver](http://cs.stmarys.ca/~muir/BVP_SOLVER_Webpage.shtml).
I'll include your proposed changes there (by hand) and backport them to the older julia versions. I hope everything will be online tomorrow.

**Comment by luchr** [comment]
I removed the `Function` dependence in the last release. I also added a test which tests this for the right-hand-side calls.
Thank you for the improvement.

**Comment by luchr** [comment]
closed because it was merged.

**Pull request closed without merging**
